### ISSUE TITLE
EpiNow2 2.0.0 roadmap

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#423]
It might be good to put together a development roadmap for EpiNow2 2.0.0. Current open Issues/Discussion would suggest

### New features:
- [ ] Fit to multiple observation time series (see design discussion at https://github.com/epiforecasts/EpiNow2/discussions/371) 
- [ ] #408  
- [ ] rename models and add (simple) covariate interface #345 
- [ ] replace `estimate_delays` with `estimate_dist` with better discretisation #350 #411
- [ ] add an optimisation option #403
### User interface
- [ ] #451
- [X] ~#191 (if deciding to do)~ not doing for now
- [ ] #346 
- [ ] #382 
- [x] #390 
- [x] #410 
### Bug fixing
- [x] #349 
- [x] #392
- [x] #420  
### Internal improvement
- [x] #381
- [x] #337   
- [x] #348 
### Documentation
- [ ] #367 which could go nicely with #353 

Quite a lot in there so some of these (especially the new features) may warrant intermediate releases.

**Comment by jamesmbaazam** [comment]
This has now been set up as a project board here https://github.com/orgs/epiforecasts/projects/7. I'm unable to make it public, I guess because I don't have those rights on the Epiforecasts org. @sbfnk can you make it public?

Also, would you like us to add all new issues to the board manually or do we want to do it automatically using the project workflows rules?

**Comment by sbfnk** [comment]
> This has now been set up as a project board here [github.com/orgs/epiforecasts/projects/7](https://github.com/orgs/epiforecasts/projects/7). I'm unable to make it public, I guess because I don't have those rights on the Epiforecasts org. @sbfnk can you make it public?

Done

> Also, would you like us to add all new issues to the board manually or do we want to do it automatically using the project workflows rules?

If they are added automatically can we then use the project board to decide whether they get added to the release or not? At some point we'll want to release and leave some issues behind.

**Comment by jamesmbaazam** [comment]
> If they are added automatically can we then use the project board to decide whether they get added to the release or not? At some point we'll want to release and leave some issues behind.

Yes, they can all go on the board and initially without a status. We can then set rules to move them across the board, for example, when a PR is opened to address them.

**Comment by sbfnk** [comment]
Closing as superseded by #552 and associate project boards.
