### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#552]
We (mostly thanks to @sbfnk) are starting to accumulate a lot of nice new features all (I think) are well implemented enough not to break backwards compatibility. Given that we should likely plan for a CRAN release in the near future. Especially as some of the larger changes may have to lead to breaking changes.

**Comment by sbfnk** [comment]
Question is whether we do this now or wait until the 2.0.0 release (#423) is ready. Given quite substantial further development that will be needed especially to update the observation model and covariate interface I agree that there might be a case for an intermediate release as long as we're fairly confident that features have stabilised (avoiding repeating the introduction/deprecation of `dist_spec` necessitated by the `{rstan}` update).

**Comment by sbfnk** [comment]
Yes, I agree. Probably worth just waiting until we're happy the distribution interface and then going through some of the minor issues for release?

**Comment by seabbs** [comment]
Agree. Its at essentially the same point as #538 can happen imo

**Comment by sbfnk** [comment]
There now is a project board at https://github.com/orgs/epiforecasts/projects/9 with the fairly minor issues that might be nice to tackle for this.

**Comment by sbfnk** [comment]
There are still quite a few updates in the [2.0.0 plan](https://github.com/orgs/epiforecasts/projects/7). It might be nice to plan for a few intermediate releases which brings in each of these separately, followed by a "clean" 2.0.0 release where all deprecated functions are removed.

**Comment by sbfnk** [comment]
Tentatively:
- [ ] 1.5.0: new distribution interface #382 
- [ ] 1.6.0: extend distribution interface to continuous parameters #525 
- [ ] 1.7.0: covariate interface #345 
- [ ] 1.8.0: combine `estimate_infections` and `estimate_secondary` stan models into one #601 
- [ ] 1.9.0: support multiple observation time series #371 
- [ ] 2.0.0: clean version with deprecated functionality removed

Other minor issues can slot in where they fit in and major ones left to later releases.
